baseurl = "/"
title = "Bioconductor"
theme = "hugo-universal-theme"
# themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""

# Define the number of posts per page
paginate = 50

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 10

[[menu.main]]
    identifier="schedule"
    name = "Schedule"
    url  = "/schedule/"
    weight = 20

#[[menu.main]]
#    identifier="Workshops"
#    name = "Workshops & demos"
#    url  = "/workshops/"
#    weight = 22

#[[menu.main]]
#    identifier="Package demos"
#    name = "Package demos"
#    url  = "/package-demo/"
#    weight = 22

[[menu.main]]
    identifier = "sponsors"
    name = "Sponsors"
    url  = "/sponsors/"
    weight = 50

[[menu.main]]
    identifier = "about"
    name = "About"
    url  = "#"
    weight = 60

[[menu.main]]
    identifier = "submissions"
#    parent = "about"
    name = "Submissions"
    url  = "/submissions/"
    weight = 15

# [[menu.main]]
#    identifier="registration"
#    parent = "about"
#    name = "Registration"
#    url  = "/registration/"
#    weight = 55

#[[menu.main]]
#    identifier="workshops"
#    name = "Workshops"
#    url  = "/workshops-status/"
#    weight = 4

# https://github.com/devcows/hugo-universal-theme/issues/34
[[menu.main]]
    identifier = "organizers"
    parent = "about"
    name = "Organizers"
    url  = "/organizers/"
    weight = 6

[[menu.main]]
    identifier = "code"
    parent = "about"
    name = "Code of conduct"
    url  = "/code/"
    weight = 8

[[menu.main]]
    identifier = "conferences"
    parent = "about"
    name = "Past events"
    url  = "/conferences/"
    weight = 9

#[[menu.main]]
#    identifier = "conferences"
#    name = "Past events"
#    url  = "/conferences/"
#    weight = 9

# [[menu.main]]
#     identifier = "contact"
#     name = "Contact"
#     url  = "/contact/"
#     weight = 8

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/Bioconductor/"
    pre = "<i class='fab fa-2x fa-github'></i>"

# [[menu.topbar]]
#     weight = 2
#     name = "Facebook"
#     url = "http://facebook.com"
#     pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/Bioconductor"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:eurobioc@bioconductor.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 5
    name = "Slack"
    url = "https://slack.bioconductor.org/"
    pre = "<i class='fab fa-2x fa-slack'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["Bioconductor", "EuroBioC2023", "conference"]
    mainSections = ["blog"]
    # defaultDescription = "Site template made by devcows using hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "Bioconductor" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    #email = "your@email.com"
    #contact_form_ajax = false

    about_us = "<p>Bioconductor conference highlights current developments within and beyond the Bioconductor project.</p>"
    copyright = "Copyright (c) 2020 - 2023, Bioconductor."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo.png"
    address = """<p class="text-uppercase"><strong><a href="http://bioconductor.org/" target="_blank">Bioconductor web site</a></strong></p>
        <p><a href="http://bioconductor.org/about" target="_blank">About Bioconductor</a>
        <br><a href="http://bioconductor.org/help" target="_blank">Getting help</a>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Join/follow our community</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.speakers]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/speakers'.
    # For more informtion take a look at the README.
    title = "Speakers"
    # subtitle = "Confirmed speakers"

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Sponsors"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

[markup.goldmark.renderer]
unsafe= true
